// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAq7Nxwq_bjv-H-0KvI60aZkJ_sORyPs8',
    appId: '1:248321400997:web:293fcd2e4d2077826bad4c',
    messagingSenderId: '248321400997',
    projectId: 'the-splendid-market',
    authDomain: 'the-splendid-market.firebaseapp.com',
    storageBucket: 'the-splendid-market.appspot.com',
    measurementId: 'G-DEKLLSSW5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF_GwtlL12E0gw9kQdvVoKQF98PqQ35ms',
    appId: '1:248321400997:android:3eb2422937f263b66bad4c',
    messagingSenderId: '248321400997',
    projectId: 'the-splendid-market',
    storageBucket: 'the-splendid-market.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv4wR-8fRdAop4B6b8Zb9rj91SlvmDBfI',
    appId: '1:248321400997:ios:1d4d65c0c06d059e6bad4c',
    messagingSenderId: '248321400997',
    projectId: 'the-splendid-market',
    storageBucket: 'the-splendid-market.appspot.com',
    iosBundleId: 'com.spiiiq.social',
  );
}
